### ISSUE TITLE
 Product list

### ISSUE THREAD

**Issue by Louisvanderweck** [Louisvanderweck/capstone-project#1]
## Value Proposition

**As a User**  
**I want to see all products on the page**   
**so that I'm able to see which product i can buy and what the price is** 
​

## Description

![Bildschirm­foto 2023-03-19 um 14 57 39](https://user-images.githubusercontent.com/123375280/226180979-02ddd2a0-704a-4547-905d-eead7e77b5da.png)

​

## Acceptance Criteria

- [x] All products are visible on one page ​
- [x] the products are listed below each other 
- [x] you can scroll through the page

## Tasks

- [x] Fetch the fake API / or create a product.js with fake data
- [x] Create a card component with the fetched data
- [x] show several card components in a list 
​

## Complexity

M
