### ISSUE TITLE
Product filter

### ISSUE THREAD

**Issue by Louisvanderweck** [Louisvanderweck/capstone-project#2]
## Value Proposition

**As a User** 
**I want to filter the product list according to different parameters**   
**so that i can sort the list for each product**  

​

## Description

![Bildschirm­foto 2023-03-19 um 20 40 19](https://user-images.githubusercontent.com/123375280/226204804-5c1dae61-0c97-468d-a331-6445be107f09.png)

​

## Acceptance Criteria

- [ ] there is the possibility to sort the products by a filter 
- [ ] they are sorted by 3 categories (Ring, Kette, Ohrring)
- [ ] when filter is not used all products are shown
      ​

## Tasks

- [ ] create a filter component with 3 categories 
- [ ] implement the filter 
- [ ] update the shown products       ​
