### ISSUE TITLE
User Story - product page  

### ISSUE THREAD

**Issue by Louisvanderweck** [Louisvanderweck/capstone-project#5]
## Value Proposition

**As a User**  
I want to see the selected product displayed on a separate page
so that I'm able to see more details about the product. 
​

## Description
​
![Bildschirmfoto 2023-04-06 um 14 10 50](https://user-images.githubusercontent.com/123375280/230375862-ca4cc3c9-bd72-4b3b-b27a-6a105b95031f.png)

## Acceptance Criteria

- [x] the selected product is displayed on a product details page 
- [x] the product details are shown on the details page 
- [x] there is the possibility to select the material of the product
- [x] You can choose the amount of products you want to have

      ​

## Tasks

- [x] create details page 
- [x] implement dynamic routing to details page  
- [x] simple styling 

      ​

## Complexity

M
