### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by Louisvanderweck** [Louisvanderweck/capstone-project#6]
## Value Proposition

**As a** User
**I want to** navigate through the pages 
**so that** that i can navigate through the pages
​

## Description

![Bildschirmfoto 2023-04-06 um 16 39 32](https://user-images.githubusercontent.com/123375280/230413133-b5a92fbf-38e5-40de-aa99-bc26b3d69056.png)

## Acceptance Criteria

- [ ] there is a Navigation bar to change from details page to home 
- [ ] the navigation bar should shown on each page
      ​

## Tasks

- [ ] create a navigation bar component 
- [ ] implement them on each page and make the Navigation work 
- [ ] implement the correct links 

      ​

## Complexity

S

**Comment by toshydev** [comment]
You shouldn't implement the nav bar before there is any content to navigate between. Maybe change the order of user stories. I see your next US-5 has more important features to implement before adding a nav bar.
