### ISSUE TITLE
User Story - shopping card

### ISSUE THREAD

**Issue by Louisvanderweck** [Louisvanderweck/capstone-project#7]
## Value Proposition

**As a** User
**I want to** add products to the shopping card
**so that** i can select the products I want to buy     
​

## Description

![Bildschirmfoto 2023-04-06 um 17 41 32](https://user-images.githubusercontent.com/123375280/230429791-6177c998-1269-4342-a187-6b292c35449d.png)

## Acceptance Criteria

- [ ] all selected products should be shown on the shopping card  
- [ ] there should be a delete button for each product 
- [ ] in the shopping card you can choose the amount of each product 

      ​

## Tasks

- [ ] create shopping card component 
- [ ] add a delete button to each product in the shopping card
- [ ] implement the possibility to change the amount of products  
- [ ] add the shopping card to Navigation bar 

      ​

## Complexity

L

**Comment by toshydev** [comment]
LGTM 👌
